interface ExportOptions {
  filename: string
  title?: string
}

export async function exportToExcel(data: any[], options: ExportOptions) {
  if (!data || data.length === 0) return

  const XLSX = await import('xlsx')

  // Create a new workbook and worksheet
  const workbook = XLSX.utils.book_new()
  
  // Convert JSON to sheet
  const worksheet = XLSX.utils.json_to_sheet(data)

  // Append sheet to workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Report')

  // Generate and download
  XLSX.writeFile(workbook, `${options.filename}.xlsx`)
}

export async function exportToPDF(data: any[], options: ExportOptions) {
  if (!data || data.length === 0) return

  const { default: jsPDF } = await import('jspdf')
  await import('jspdf-autotable')

  const doc = new jsPDF()
  
  // Extract headers from the first object
  const headers = Object.keys(data[0])
  
  // Extract rows
  const rows = data.map(item => headers.map(key => String(item[key] || '')))

  // Add Title
  if (options.title) {
    doc.setFontSize(16)
    doc.text(options.title, 14, 22)
  }

  // Add Date
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 30)

  // Generate Table
  ;(doc as any).autoTable({
    head: [headers],
    body: rows,
    startY: 36,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [41, 128, 185] },
    margin: { top: 30 },
    didDrawPage: function (data: any) {
      // Footer
      const str = 'Generated by MealPlan on ' + new Date().toLocaleDateString()
      doc.setFontSize(8)
      doc.setTextColor(150)
      doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 10)
    }
  })

  doc.save(`${options.filename}.pdf`)
}
