import type { Handler, HandlerEvent } from '@netlify/functions'
import { createReqRes } from '../_netlify_shim.js'
import { createClient, SupabaseClient } from '@supabase/supabase-js'
import { checkRateLimit, RATE_LIMITS, getClientIP, logSecurityEvent } from '../_security.js'
import { maskEmail } from '../_validation.js'

let supabase: SupabaseClient<any, any, any>

const allowedOrigins = (process.env.ALLOWED_ORIGINS || 'http://localhost:5173').split(',').map(o => o.trim())

type UserRole = 'employee' | 'admin' | 'food_editor' | 'finance_editor'

// Verify token and return user with role
async function verifyTokenWithRole(token: string): Promise<{ user: any, role: UserRole } | null> {
  const { data: { user }, error } = await supabase.auth.getUser(token)
  if (error || !user) return null

  const { data: profile, error: profileError } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .single()

  if (profileError) return null

  return { user, role: profile?.role as UserRole }
}

// Check if role can manage meals (admin or food_editor)
function canManageMeals(role: UserRole): boolean {
  return ['admin', 'food_editor'].includes(role)
}

type ScheduleItem = {
  meal_id: string
  day_of_week?: number | null
  day_of_month?: number | null
  time_slot: string
  capacity?: number | null
  ordering_deadline_hours?: number | null
  meal_type?: 'employee' | 'student' | 'both' | null
  price?: number | null
}

function normalizeType(t: any): 'employee' | 'student' | 'both' {
  return t === 'student' || t === 'both' ? t : 'employee'
}

// Day number (0-6 weekly / 1-31 monthly) for a yyyy-MM-dd date string
function dayNumberForDate(dateStr: string, routineType: string): number {
  const d = new Date(`${dateStr}T00:00:00`)
  return routineType === 'monthly' ? d.getDate() : d.getDay()
}

function itemMatchesDate(item: ScheduleItem, dateStr: string, routineType: string): boolean {
  const n = dayNumberForDate(dateStr, routineType)
  return routineType === 'monthly' ? item.day_of_month === n : item.day_of_week === n
}

// Delete all calendar meals generated by a routine.
// Employee schedules cascade-delete their bookings (same as manual schedule deletion).
// Student tiffin rows referenced by active orders are kept (FK is RESTRICT) and
// simply unlinked from the routine via the ON DELETE SET NULL foreign key.
async function deleteRoutineSchedules(routineId: string) {
  await supabase.from('menu_schedules').delete().eq('routine_id', routineId)

  const { data: studentRows } = await supabase
    .from('student_tiffin_menu')
    .select('id')
    .eq('routine_id', routineId)

  const ids = (studentRows || []).map((r: any) => r.id)
  if (ids.length === 0) return

  const { data: activeOrders } = await supabase
    .from('student_orders')
    .select('tiffin_menu_id')
    .in('tiffin_menu_id', ids)
    .not('status', 'eq', 'cancelled')

  const blocked = new Set((activeOrders || []).map((o: any) => o.tiffin_menu_id))
  const deletable = ids.filter((id: string) => !blocked.has(id))
  if (deletable.length > 0) {
    await supabase.from('student_tiffin_menu').delete().in('id', deletable)
  }
}

// Reconcile the already-scheduled (future) rows of a single table with the
// routine's current items, restricted to dates the routine already covers.
async function syncScheduleTable(
  table: 'menu_schedules' | 'student_tiffin_menu',
  routineId: string,
  routineType: string,
  today: string,
  applicableItems: ScheduleItem[],
  buildInsert: (item: ScheduleItem, dateStr: string) => any,
  buildUpdate: (item: ScheduleItem) => any,
  kind: 'employee' | 'student' = 'employee'
) {
  const { data: existing } = await supabase
    .from(table)
    .select('id, meal_id, scheduled_date, time_slot')
    .eq('routine_id', routineId)
    .gte('scheduled_date', today)

  const existingRows = (existing || []) as any[]
  if (existingRows.length === 0) return // routine was never applied to this audience

  const coveredDates = Array.from(new Set(existingRows.map(r => r.scheduled_date)))

  // Desired rows keyed by `${date}|${time_slot}`
  const desired = new Map<string, ScheduleItem>()
  for (const dateStr of coveredDates) {
    for (const item of applicableItems) {
      if (itemMatchesDate(item, dateStr, routineType)) {
        desired.set(`${dateStr}|${item.time_slot}`, item)
      }
    }
  }

  const toDelete: string[] = []
  const matchedKeys = new Set<string>()

  for (const row of existingRows) {
    const key = `${row.scheduled_date}|${row.time_slot}`
    const item = desired.get(key)
    if (item) {
      matchedKeys.add(key)
      await supabase.from(table).update(buildUpdate(item)).eq('id', row.id)
    } else {
      toDelete.push(row.id)
    }
  }

  // Remove schedule rows whose routine item no longer exists
  if (toDelete.length > 0) {
    if (kind === 'student') {
      const { data: activeOrders } = await supabase
        .from('student_orders')
        .select('tiffin_menu_id')
        .in('tiffin_menu_id', toDelete)
        .not('status', 'eq', 'cancelled')
      const blocked = new Set((activeOrders || []).map((o: any) => o.tiffin_menu_id))
      const deletable = toDelete.filter(id => !blocked.has(id))
      if (deletable.length > 0) await supabase.from(table).delete().in('id', deletable)
    } else {
      await supabase.from(table).delete().in('id', toDelete)
    }
  }

  // Insert rows for newly added items on already-covered dates
  const toInsert: any[] = []
  for (const [key, item] of desired.entries()) {
    if (!matchedKeys.has(key)) {
      const dateStr = key.split('|')[0]
      toInsert.push(buildInsert(item, dateStr))
    }
  }
  if (toInsert.length > 0) {
    await supabase.from(table).insert(toInsert)
  }
}

// Propagate a routine edit to the future calendar meals generated from it.
async function syncRoutineSchedules(routineId: string, routineType: string, items: ScheduleItem[]) {
  const today = new Date().toISOString().slice(0, 10)
  const normalized = items.map(it => ({ ...it, meal_type: normalizeType(it.meal_type) }))

  await syncScheduleTable(
    'menu_schedules',
    routineId,
    routineType,
    today,
    normalized.filter(it => it.meal_type === 'employee' || it.meal_type === 'both'),
    (item, dateStr) => ({
      meal_id: item.meal_id,
      scheduled_date: dateStr,
      time_slot: item.time_slot,
      capacity: item.capacity || 10,
      is_available: true,
      booking_time_limit: item.ordering_deadline_hours || 1,
      ordering_deadline_hours: item.ordering_deadline_hours || 1,
      price: item.price ?? null,
      routine_id: routineId
    }),
    (item) => ({
      meal_id: item.meal_id,
      capacity: item.capacity || 10,
      booking_time_limit: item.ordering_deadline_hours || 1,
      ordering_deadline_hours: item.ordering_deadline_hours || 1,
      price: item.price ?? null
    }),
    'employee'
  )

  await syncScheduleTable(
    'student_tiffin_menu',
    routineId,
    routineType,
    today,
    normalized.filter(it => it.meal_type === 'student' || it.meal_type === 'both'),
    (item, dateStr) => ({
      meal_id: item.meal_id,
      scheduled_date: dateStr,
      time_slot: item.time_slot,
      capacity: item.capacity || 10,
      price: item.price || 0,
      is_available: true,
      ordering_deadline_hours: item.ordering_deadline_hours || 1,
      routine_id: routineId
    }),
    (item) => ({
      meal_id: item.meal_id,
      capacity: item.capacity || 10,
      price: item.price || 0,
      ordering_deadline_hours: item.ordering_deadline_hours || 1
    }),
    'student'
  )
}

export const handler: Handler = async (event: HandlerEvent) => {
  const supabaseUrl = process.env.VITE_SUPABASE_URL
  const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!supabaseUrl || !supabaseServiceKey) {
    return {
      statusCode: 500,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        success: false, 
        error: 'Server configuration error' 
      })
    }
  }

  supabase = createClient(supabaseUrl, supabaseServiceKey)

  const { req, res } = createReqRes(event)
  const origin = req.headers.origin
  const clientIP = getClientIP(req)

  // Handle CORS
  if (origin && allowedOrigins.includes(origin)) {
    res.setHeader('Access-Control-Allow-Origin', origin)
  } else {
    res.setHeader('Access-Control-Allow-Origin', allowedOrigins[0])
  }
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization')

  if (req.method === 'OPTIONS') {
    return res.status(200).end()
  }

  // Rate limiting check
  const rateLimitKey = `admin_routines:${clientIP}`
  const rateLimitResult = checkRateLimit(rateLimitKey, RATE_LIMITS.sensitive)
  if (!rateLimitResult.allowed) {
    return res.status(429).json({ error: 'Too many requests' })
  }

  // Verify JWT token
  const authHeader = req.headers.authorization
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Unauthorized' })
  }

  const token = authHeader.split('Bearer ')[1]

  try {
    const auth = await verifyTokenWithRole(token)
    if (!auth || !canManageMeals(auth.role)) {
      return res.status(403).json({ error: 'Forbidden' })
    }

    const { user } = auth

    if (req.method === 'GET') {
      const { data, error } = await supabase
        .from('meal_routines')
        .select(`
          *,
          items:meal_routine_items(
            *,
            meal:meals(name, meal_type)
          )
        `)
        .order('created_at', { ascending: false })

      if (error) throw error

      return res.status(200).json(data)
    }

    if (req.method === 'POST') {
      const { name, description, routine_type, items } = req.body

      if (!name || !routine_type || !items || !Array.isArray(items)) {
        return res.status(400).json({ error: 'Invalid input' })
      }

      // 1. Create the routine
      const { data: routine, error: routineError } = await supabase
        .from('meal_routines')
        .insert({
          name,
          description: description || null,
          routine_type,
          is_active: true,
          created_by: user.id
        })
        .select()
        .single()

      if (routineError) throw routineError

      // 2. Insert the items
      const itemsToInsert = items.map(item => ({
        routine_id: routine.id,
        meal_id: item.meal_id,
        day_of_week: item.day_of_week ?? null,
        day_of_month: item.day_of_month ?? null,
        time_slot: item.time_slot,
        capacity: item.capacity || 10,
        ordering_deadline_hours: item.ordering_deadline_hours || 1,
        meal_type: item.meal_type || 'employee',
        price: item.price || null
      }))

      if (itemsToInsert.length > 0) {
        const { error: itemsError } = await supabase
          .from('meal_routine_items')
          .insert(itemsToInsert)

        if (itemsError) throw itemsError
      }

      logSecurityEvent('ADMIN_ACTION', req, {
        userId: user.id,
        email: maskEmail(user.email || ''),
        severity: 'INFO',
        details: { action: 'ROUTINE_CREATED', routineId: routine.id, itemsCount: itemsToInsert.length }
      })

      return res.status(201).json({ success: true, routine })
    }

    if (req.method === 'PUT') {
      const { id, name, description, items } = req.body

      if (!id) {
        return res.status(400).json({ error: 'Routine id is required' })
      }
      if (!Array.isArray(items)) {
        return res.status(400).json({ error: 'Invalid input' })
      }

      // 1. Remove existing items for this routine
      const { error: deleteItemsError } = await supabase
        .from('meal_routine_items')
        .delete()
        .eq('routine_id', id)

      if (deleteItemsError) throw deleteItemsError

      // 2. Re-insert new items
      const itemsToInsert = items.map(item => ({
        routine_id: id,
        meal_id: item.meal_id,
        day_of_week: item.day_of_week ?? null,
        day_of_month: item.day_of_month ?? null,
        time_slot: item.time_slot,
        capacity: item.capacity || 10,
        ordering_deadline_hours: item.ordering_deadline_hours || 1,
        meal_type: item.meal_type || 'employee',
        price: item.price || null
      }))

      if (itemsToInsert.length > 0) {
        const { error: itemsError } = await supabase
          .from('meal_routine_items')
          .insert(itemsToInsert)

        if (itemsError) throw itemsError
      }

      // 3. Update routine name and description
      const { data: routine, error: updateError } = await supabase
        .from('meal_routines')
        .update({
          name,
          description: description || null
        })
        .eq('id', id)
        .select()
        .single()

      if (updateError) throw updateError

      // 4. Propagate the edit to future calendar meals generated from this routine
      await syncRoutineSchedules(id, routine.routine_type, items)

      logSecurityEvent('ADMIN_ACTION', req, {
        userId: user.id,
        email: maskEmail(user.email || ''),
        severity: 'INFO',
        details: { action: 'ROUTINE_UPDATED', routineId: id, itemsCount: itemsToInsert.length }
      })

      return res.status(200).json({ success: true, routine })
    }

    if (req.method === 'DELETE') {
      const { id } = req.body

      if (!id) {
        return res.status(400).json({ error: 'Routine id is required' })
      }

      // 1. Delete calendar meals generated from this routine
      await deleteRoutineSchedules(id)

      // 2. Delete routine items
      const { error: itemsError } = await supabase
        .from('meal_routine_items')
        .delete()
        .eq('routine_id', id)

      if (itemsError) throw itemsError

      // 3. Delete the routine
      const { error: routineError } = await supabase
        .from('meal_routines')
        .delete()
        .eq('id', id)

      if (routineError) throw routineError

      logSecurityEvent('ADMIN_ACTION', req, {
        userId: user.id,
        email: maskEmail(user.email || ''),
        severity: 'INFO',
        details: { action: 'ROUTINE_DELETED', routineId: id }
      })

      return res.status(200).json({ success: true })
    }

    return res.status(405).json({ error: 'Method not allowed' })
  } catch (error: any) {
    console.error('Routine API error:', error)
    return res.status(500).json({
      error: 'Internal server error',
      detail: error?.message || String(error),
      code: error?.code,
      hint: error?.hint,
    })
  }
}
